import NavDashboard from '@/components/molecules/NavDashboard';
import Navigation from '@/components/molecules/Navigation';
import Search from '@/components/atoms/Search';
import StaticMeta from '@/components/atoms/StaticMeta';
import Table from '@/components/molecules/Table';
import { useDarkMode } from '@/context/DarkModeContext';
import { useState, useEffect } from 'react';
import svg from '@/public/images/svg/drop.png';
const axios = require('axios');

const RegistroInseminacion = ({ title, description, image }) => {
  const { isDarkMode, toggleDarkMode } = useDarkMode();
  const [data, setData] = useState([
    {
      usuario: 'lorem',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem3',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'hola',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'hola',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem3',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'hola',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'hola',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem3',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'hola',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'hola',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem3',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'hola',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'hola',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'lorem3',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'hola',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
    {
      usuario: 'hola',
      password: 'lorem',
      email: 'lorem',
      nombre: 'lorem',
      apellido: 'lorem',
      fechaNacimiento: 'lorem',
      genero: 'lorem',
      puesto: 'lorem',
      salario: 'lorem',
      horario: 'lorem',
      fechaContratacion: 'lorem',
      departamento: 'lorem',
      statu: 'lorem',
      contacto: 'lorem',
      grupo: 'lorem',
      calle: 'lorem',
      ciudad: 'lorem',
      estado: 'lorem',
      cp: 'lorem',
      id: 'lorem',
      nombreGrupo: 'lorem',
    },
  ]);

  useEffect(() => {
    axios
      .get('http://192.168.100.10:3030/getAllMedicamento')
      .then((response) => {
        const jsonData = response.data;
        setData(jsonData.data);
      })
      .catch((error) => {
        console.error(error);
      });
  }, []);

  return (
    <div className={`${isDarkMode ? 'darkMode' : 'lightMode'} full-viewport`}>
      <StaticMeta title={title} description={description} image={image} />
      <div>
        <Navigation />
        <NavDashboard section="Inseminación" svg={svg} />
      </div>
      <div className="wrapper">
        <h2 className="text-xl mt-5 mb-5">Elementos existentes</h2>
        <div className="mt-10">
          <Table data={data} setData={setData} />
        </div>
      </div>
    </div>
  );
};
export default RegistroInseminacion;

export const getServerSideProps = async () => {
  const title = 'Constanza';
  const description = 'Dashboard de inseminacion';
  const image = 'images/icon/logo-400.png';
  return {
    props: {
      title,
      description,
      image,
    },
  };
};
