questions_dir: "preguntas.csv"
#
ModelEmbeddingRetriever : "sentence-transformers/all-mpnet-base-v2"
ModelQuestionAnswering: "distilbert-base-cased-distilled-squad"
#direccion IP 
connection_url : "mongodb://pigpig:0iEF&C84k4gqe&d&2D38%5EtNb&xln6d03hXLOGAcbY0LeRGUlGj@192.168.100.10:27017/"
#nombre de la base de datos(General)
db_name : 'C3_LaPurisima'
#Nombre de la base de datos de transportes
table_name_transportes: 'transportePrueba'